#!/usr/bin/env bash
set -euo pipefail

# Production deployment helper for Goozi using docker-compose
# - Creates/updates .env with production URLs and secrets
# - Builds and starts production containers
# - Runs migrations and creates admin user

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  echo "[ERROR] Please run as root (use: sudo bash devops/setup-prod.sh)"
  exit 1
fi

cd "$(dirname "${BASH_SOURCE[0]}")/.."

if ! command -v docker >/dev/null 2>&1; then
  echo "❌ Docker is not installed. Please run devops/setup-ubuntu.sh first."
  exit 1
fi

if ! command -v docker-compose >/dev/null 2>&1 && ! docker compose version >/dev/null 2>&1; then
  echo "❌ docker-compose or docker compose is not available. Please run devops/setup-ubuntu.sh first."
  exit 1
fi

echo "==> Configuring production environment (.env)..."

WEB_DEFAULT="https://web.goozi.org"
CMS_DEFAULT="https://cms.goozi.org"
API_DEFAULT="https://api.goozi.org"

read -rp "Frontend Web URL [${WEB_DEFAULT}]: " FRONTEND_URL
FRONTEND_URL=${FRONTEND_URL:-$WEB_DEFAULT}

read -rp "CMS Admin URL [${CMS_DEFAULT}]: " CMS_URL
CMS_URL=${CMS_URL:-$CMS_DEFAULT}

read -rp "Backend API URL (base, without /api) [${API_DEFAULT}]: " API_URL
API_URL=${API_URL:-$API_DEFAULT}

read -rp "Google OAuth Client ID (optional, Enter to skip): " GOOGLE_CLIENT_ID
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}

JWT_SECRET_VALUE="$(openssl rand -hex 32)"

cat > .env <<EOF
# Generated by devops/setup-prod.sh

# Database
DB_HOST=postgres
DB_PORT=5432
DB_NAME=goozi_db
DB_USER=postgres
DB_PASSWORD=postgres

# JWT
JWT_SECRET=${JWT_SECRET_VALUE}
JWT_EXPIRES_IN=7d

# Server
PORT=3001
NODE_ENV=production

# CORS / allowed origins
FRONTEND_URL=${FRONTEND_URL}
CMS_URL=${CMS_URL}

# Google OAuth
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}

# Frontend Build Args
VITE_API_URL=${API_URL}/api
VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
EOF

echo "✅ .env written for production."

echo "==> Building production images..."
docker-compose build

echo "==> Starting production containers..."
docker-compose up -d

echo "==> Waiting for database to be ready..."
sleep 15

echo "==> Running database migrations..."
docker-compose exec backend npm run migrate

echo "==> Creating admin user..."
docker-compose exec backend npm run create-admin

cat <<EOF

[OK] Production deployment completed.

Services (behind Docker, before Nginx):
  - Web: http://localhost:3000
  - CMS: http://localhost:3002
  - API: http://localhost:3001

Public URLs (via Nginx, if configured):
  - Web: ${FRONTEND_URL}
  - CMS: ${CMS_URL}
  - API: ${API_URL}

You can check containers with:
  docker-compose ps
  docker-compose logs -f

EOF

