#!/usr/bin/env bash
set -euo pipefail

# Development/Test Build & Deploy Script
# Builds and deploys Goozi in development mode with hot reload

echo "🧪 Goozi Development/Test Build & Deploy"
echo "========================================="

# Check Docker
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed. Please install Docker first."
    exit 1
fi

if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
    echo "❌ docker-compose is not installed. Please install Docker Compose first."
    exit 1
fi

# Check if .env exists, if not create from template
if [ ! -f .env ]; then
    echo ""
    echo "📝 Creating .env from template..."
    
    if [ -f .env.development.example ]; then
        cp .env.development.example .env
        echo "✅ Created .env from .env.development.example"
    else
        echo "⚠️  .env.development.example not found. Creating basic .env for development..."
        
        read -p "Google OAuth Client ID (optional, Enter to skip): " GOOGLE_CLIENT_ID
        GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
        
        JWT_SECRET=$(openssl rand -hex 32)
        
        cat > .env << EOF
# Development Environment
# Generated by build-dev.sh

# Database
DB_HOST=postgres
DB_PORT=5432
DB_NAME=goozi_db
DB_USER=postgres
DB_PASSWORD=postgres

# JWT
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=7d

# Server
PORT=3001
NODE_ENV=development

# CORS / Allowed Origins
FRONTEND_URL=http://localhost:3000
CMS_URL=http://localhost:3002

# Google OAuth
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}

# Frontend Build Args (for dev, these are overridden by docker-compose.dev.yml)
VITE_API_URL=http://localhost:3001/api
VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
EOF
        echo "✅ Created .env file"
    fi
fi

echo ""
echo "📋 Development Configuration:"
echo "   Frontend Web: http://localhost:3000"
echo "   CMS Admin:    http://localhost:3002"
echo "   Backend API:  http://localhost:3001/api"
echo ""

read -p "Continue with build? [y/N]: " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "❌ Build cancelled"
    exit 1
fi

# Stop existing containers
echo ""
echo "🛑 Stopping existing containers..."
docker-compose -f docker-compose.dev.yml down 2>/dev/null || true

# Build development images
echo ""
echo "🏗️  Building development images..."
docker-compose -f docker-compose.dev.yml build --no-cache

# Start containers
echo ""
echo "🚀 Starting development containers..."
docker-compose -f docker-compose.dev.yml up -d

# Wait for database
echo ""
echo "⏳ Waiting for database to be ready..."
sleep 10

# Run migrations
echo ""
echo "📦 Running database migrations..."
docker-compose -f docker-compose.dev.yml exec -T backend npm run migrate || {
    echo "⚠️  Migration failed, but continuing..."
}

# Create admin user
echo ""
echo "👤 Creating admin user..."
docker-compose -f docker-compose.dev.yml exec -T backend npm run create-admin || {
    echo "⚠️  Admin creation failed (may already exist)"
}

# Display status
echo ""
echo "✅ Development environment ready!"
echo ""
echo "📊 Container Status:"
docker-compose -f docker-compose.dev.yml ps
echo ""
echo "🌐 Services (with hot reload):"
echo "   - Frontend Web: http://localhost:3000"
echo "   - CMS Admin:    http://localhost:3002"
echo "   - Backend API:  http://localhost:3001/api"
echo ""
echo "📝 Useful Commands:"
echo "   View logs:      docker-compose -f docker-compose.dev.yml logs -f"
echo "   Stop services:  docker-compose -f docker-compose.dev.yml down"
echo "   Restart:        docker-compose -f docker-compose.dev.yml restart [service]"
echo "   Rebuild one:    docker-compose -f docker-compose.dev.yml build --no-cache [service] && docker-compose -f docker-compose.dev.yml up -d [service]"
echo ""
echo "💡 Hot reload is enabled - code changes will automatically reload!"
echo ""
