#!/usr/bin/env bash
set -euo pipefail

# Production Build & Deploy Script
# Builds and deploys Goozi in production mode

echo "🏭 Goozi Production Build & Deploy"
echo "===================================="

# Check Docker
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed. Please install Docker first."
    exit 1
fi

if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
    echo "❌ docker-compose is not installed. Please install Docker Compose first."
    exit 1
fi

# Check if .env exists, if not create from template
if [ ! -f .env ]; then
    echo ""
    echo "📝 Creating .env from template..."
    
    if [ -f .env.production.example ]; then
        cp .env.production.example .env
        echo "✅ Created .env from .env.production.example"
        echo "⚠️  Please edit .env and set your production URLs before continuing."
        echo ""
        read -p "Press Enter after editing .env, or Ctrl+C to cancel..."
    else
        echo "⚠️  .env.production.example not found. Creating basic .env..."
        
        read -p "Frontend Web URL (e.g., https://web.goozi.org): " FRONTEND_URL
        read -p "CMS Admin URL (e.g., https://cms.goozi.org): " CMS_URL
        read -p "Backend API URL (e.g., https://api.goozi.org): " API_URL
        read -p "Google OAuth Client ID (optional, Enter to skip): " GOOGLE_CLIENT_ID
        
        FRONTEND_URL=${FRONTEND_URL:-https://web.goozi.org}
        CMS_URL=${CMS_URL:-https://cms.goozi.org}
        API_URL=${API_URL:-https://api.goozi.org}
        GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
        
        JWT_SECRET=$(openssl rand -hex 32)
        
        cat > .env << EOF
# Production Environment
# Generated by build-prod.sh

# Database
DB_HOST=postgres
DB_PORT=5432
DB_NAME=goozi_db
DB_USER=postgres
DB_PASSWORD=postgres

# JWT
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=7d

# Server
PORT=3001
NODE_ENV=production

# CORS / Allowed Origins
FRONTEND_URL=${FRONTEND_URL}
CMS_URL=${CMS_URL}

# Google OAuth
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}

# Frontend Build Args
VITE_API_URL=${API_URL}/api
VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
EOF
        echo "✅ Created .env file"
    fi
fi

# Load .env to check values
source .env 2>/dev/null || true

echo ""
echo "📋 Current Configuration:"
echo "   Frontend Web: ${FRONTEND_URL:-not set}"
echo "   CMS Admin:    ${CMS_URL:-not set}"
echo "   Backend API:  ${VITE_API_URL:-not set}"
echo ""

read -p "Continue with build? [y/N]: " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "❌ Build cancelled"
    exit 1
fi

# Stop existing containers
echo ""
echo "🛑 Stopping existing containers..."
docker-compose down 2>/dev/null || true

# Build production images
echo ""
echo "🏗️  Building production images..."
docker-compose build --no-cache

# Start containers
echo ""
echo "🚀 Starting production containers..."
docker-compose up -d

# Wait for database
echo ""
echo "⏳ Waiting for database to be ready..."
sleep 15

# Run migrations
echo ""
echo "📦 Running database migrations..."
docker-compose exec -T backend npm run migrate || {
    echo "⚠️  Migration failed, but continuing..."
}

# Create admin user
echo ""
echo "👤 Creating admin user..."
docker-compose exec -T backend npm run create-admin || {
    echo "⚠️  Admin creation failed (may already exist)"
}

# Display status
echo ""
echo "✅ Production deployment complete!"
echo ""
echo "📊 Container Status:"
docker-compose ps
echo ""
echo "🌐 Services:"
echo "   - Frontend Web: ${FRONTEND_URL:-http://localhost:3000}"
echo "   - CMS Admin:    ${CMS_URL:-http://localhost:3002}"
echo "   - Backend API:  ${VITE_API_URL:-http://localhost:3001/api}"
echo ""
echo "📝 Useful Commands:"
echo "   View logs:      docker-compose logs -f"
echo "   Stop services:  docker-compose down"
echo "   Restart:        docker-compose restart [service]"
echo "   Rebuild one:    docker-compose build --no-cache [service] && docker-compose up -d [service]"
echo ""
